import Head from 'next/head'
import { Button } from '../src/components/atoms/Button/Button'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Opa</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        Something goes here
        <Button>Hello</Button>
      </main>
    </div>
  )
}
